const sellCategories = [
  "gowns",
  "maternity-gowns",
  "pre-wedding-gowns",
  "engagement-gowns",
  "party-wear-gowns",
  "dresses",
  "short-dresses",
  "party-wear-dresses",
  "accessories",
  "tiara",
  "cancan-skirt",
];

const rentCategories = [
  "gowns",
  "maternity-gowns",
  "pre-wedding-gowns",
  "engagement-gowns",
  "party-wear-gowns",
  "dresses",
  "short-dresses",
  "party-wear-dresses",
  "lehenga",
  "accessories",
  "sarees",
  "tiara",
];

const publicPages = {
  "/": "homepage",
  "my-bag": "bag",
  "my-wishlist": "wishlist",
  contact: "contact",
  "about-us": "about",
  rental: "rental-home",
};

const policyPages = {
  "terms-and-condition": "termsAndCondition",
  "privacy-policy": "privacyPolicy",
  "shipping-policy": "shippingPolicy",
  "cancellation-and-exchange-policy": "cancellationAndExchangePolicy",
};

const stateNames = [
  "Andaman And Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu And Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "The Dadra And Nagar Haveli And Daman And Diu",
  "Tripura",
  "Uttarakhand",
  "Uttar Pradesh",
  "West Bengal",
];

const deliveryCharges = {
  "andaman and nicobar islands": 80,
  "andhra pradesh": 80,
  "arunachal pradesh": 80,
  assam: 80,
  bihar: 80,
  chandigarh: 80,
  chhattisgarh: 80,
  delhi: 80,
  goa: 80,
  gujarat: 80,
  haryana: 80,
  "himachal pradesh": 80,
  "jammu and kashmir": 80,
  jharkhand: 80,
  karnataka: 80,
  kerala: 80,
  ladakh: 80,
  lakshadweep: 80,
  "madhya pradesh": 50,
  maharashtra: 80,
  manipur: 80,
  meghalaya: 80,
  mizoram: 80,
  nagaland: 80,
  odisha: 80,
  puducherry: 80,
  punjab: 80,
  rajasthan: 80,
  sikkim: 80,
  "tamil nadu": 80,
  telangana: 80,
  "the dadra and nagar haveli and daman and diu": 80,
  tripura: 80,
  uttarakhand: 80,
  "uttar pradesh": 80,
  "west bengal": 80,
};

useFileFrom = "localFiles";

module.exports = {
  sellCategories,
  rentCategories,
  publicPages,
  stateNames,
  policyPages,
  useFileFrom,
  deliveryCharges,
};
