const categories = [
  "gowns",
  "kids",
  "maternity-gowns",
  "sarees",
  "dresses",
  "lehengas",
  "accessories",
];

let categoryNames = {
  gowns: "GOWNS",
  kids: "KIDS DRESSES",
  sarees: "SAREES",
  dresses: "DRESSES",
  lehengas: "LEHENGAS",
  "maternity-gowns": "MATERNITY GOWNS",
  accessories: "ACCESSORIES",
};

const publicPages = {
  "/": "homepage",
  "my-bag": "bag",
  "my-wishlist": "wishlist",
  contact: "contact",
  "about-us": "about",
  photoshoot: "photoshoot",
  rental: "rental-home",
};

const stateNames = [
  "Andaman And Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu And Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "The Dadra And Nagar Haveli And Daman And Diu",
  "Tripura",
  "Uttarakhand",
  "Uttar Pradesh",
  "West Bengal",
];

module.exports = {
  categories,
  categoryNames,
  publicPages,
  stateNames,
};
